---
- name: Configure SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "{{ item }}"
    state: present
  with_items:
    - "PermitRootLogin no"
    - "PasswordAuthentication no"
    - "LogLevel VERBOSE"
    - "X11Forwarding no"

